/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postOffice;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.DayOfWeek;
import java.time.Instant;
import static java.time.Instant.now;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lakshan
 */
public class AdminSideSendDailyBillPaySummery extends javax.swing.JFrame {
 Connection conn=DBconnection.connect();
 ResultSet rs =null;
 int numberRow=0;
    /**
     * Creates new form AdminSideSendDailySummery
     */
    public AdminSideSendDailyBillPaySummery() {
        initComponents();
        
         try
        {
        String ASDBPSQuerery="select * from bill_payments";
        PreparedStatement ps =conn.prepareStatement(ASDBPSQuerery);
        //ps.execute();
        rs=ps.executeQuery();
        BillPayementCheck.setModel(DbUtils.resultSetToTableModel(rs));
       
        
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
         System.out.println(numberRow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1456 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Reset02_Channel = new javax.swing.JButton();
        Submit_Channel = new javax.swing.JButton();
        UserPass = new javax.swing.JPasswordField();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        BillPayCount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillPayementCheck = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1456.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1456.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1456.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/DOP_header.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1456.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, -1));

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/back3.png"))); // NOI18N
        jButton8.setText("GO Back");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1456.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 45));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member Portal /");
        jPanel1456.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 210, -1));

        jLabel3.setFont(new java.awt.Font("4u-Malith", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("iduðl ìysfodr");
        jPanel1456.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 350, 30));

        UserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserName.setToolTipText("");
        UserName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        jPanel1456.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, 250, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("User Name");
        jPanel1456.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Password");
        jPanel1456.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, 130, 30));

        Reset02_Channel.setBackground(new java.awt.Color(255, 51, 51));
        Reset02_Channel.setForeground(new java.awt.Color(255, 255, 255));
        Reset02_Channel.setText("Reset");
        Reset02_Channel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset02_ChannelActionPerformed(evt);
            }
        });
        jPanel1456.add(Reset02_Channel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 810, 120, 40));

        Submit_Channel.setBackground(new java.awt.Color(255, 51, 51));
        Submit_Channel.setForeground(new java.awt.Color(255, 255, 255));
        Submit_Channel.setText("login");
        Submit_Channel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_ChannelActionPerformed(evt);
            }
        });
        jPanel1456.add(Submit_Channel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 810, 120, 40));

        UserPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserPass.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1456.add(UserPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 720, 250, 30));

        panel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bill Payme t Count");
        jLabel1.setToolTipText("");

        BillPayCount.setFont(new java.awt.Font("Leelawadee UI", 0, 60)); // NOI18N
        BillPayCount.setForeground(new java.awt.Color(255, 255, 255));
        BillPayCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BillPayCount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(BillPayCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BillPayCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1456.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 150, 120));

        BillPayementCheck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BillPayementCheck);

        jPanel1456.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 660, 230));

        jButton1.setText("Select Date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1456.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        jPanel1456.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 260, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1456, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1456, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        MainMenu MM=new MainMenu();
        setVisible(false);
        MM.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void Reset02_ChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset02_ChannelActionPerformed
        // TODO add your handling code here:
        //   Cname_Channel.setText(null);
        // Nic_Channel.setText(null);
        //Cusphn_Channel.setText(null);
    }//GEN-LAST:event_Reset02_ChannelActionPerformed

    private void Submit_ChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_ChannelActionPerformed
        // TODO add your handling code here:

       
    }//GEN-LAST:event_Submit_ChannelActionPerformed

    private void jDateChooser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyPressed
        // TODO add your handling code here:.

    }//GEN-LAST:event_jDateChooser1KeyPressed

    private void jDateChooser1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1MousePressed

    private void jDateChooser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1MouseEntered

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jDateChooser1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser1AncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int a=jDateChooser1.getCalendar().get(Calendar.MONTH)+1;
        int b=jDateChooser1.getCalendar().get(Calendar.DATE);
        int c=jDateChooser1.getCalendar().get(Calendar.YEAR);
        String SelectedDate=c+"-"+"0"+a+"-"+b;
        System.out.println(SelectedDate);
        try
        {
            String SelectASDBPSQuerery="select * from bill_payments WHERE Date LIKE '%"+SelectedDate+"%'";
            PreparedStatement ps =conn.prepareStatement(SelectASDBPSQuerery);
            //ps.execute();
            rs=ps.executeQuery();
            BillPayementCheck.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        // System.out.println("Current date : " + (now.get(Calendar.MONTH) + 1) + "-"+ now.get(Calendar.DATE) + "-" + now.get(Calendar.YEAR));
        //; //
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSideSendDailyBillPaySummery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSideSendDailyBillPaySummery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSideSendDailyBillPaySummery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSideSendDailyBillPaySummery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSideSendDailyBillPaySummery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BillPayCount;
    private javax.swing.JTable BillPayementCheck;
    private javax.swing.JButton Reset02_Channel;
    private javax.swing.JButton Submit_Channel;
    private javax.swing.JTextField UserName;
    private javax.swing.JPasswordField UserPass;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel1456;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
