/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postOffice;

import static java.awt.Event.UP;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.DatatypeConverter;


/**
 *
 * @author Lakshan
 */
public class AdminSide extends javax.swing.JFrame {
String UserPassEncript=null;
ResultSet rs =null;
 PreparedStatement ps;
Connection conn=DBconnection.connect();

    /**
     * Creates new form AdminSide
     */
    public AdminSide() {
        initComponents();
      

       
    
    

      
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1456 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Reset02_Channel = new javax.swing.JButton();
        Submit_Channel = new javax.swing.JButton();
        JLabel1 = new javax.swing.JLabel();
        UserPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1456.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1456.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1456.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/DOP_header.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1456.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, -1));

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/back3.png"))); // NOI18N
        jButton8.setText("GO Back");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1456.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 45));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member Portal /");
        jPanel1456.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 210, -1));

        jLabel3.setFont(new java.awt.Font("4u-Malith", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("iduðl ìysfodr");
        jPanel1456.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 350, 30));

        UserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserName.setToolTipText("");
        UserName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        jPanel1456.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, 250, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("User Name");
        jPanel1456.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Password");
        jPanel1456.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, 130, 30));

        Reset02_Channel.setBackground(new java.awt.Color(255, 51, 51));
        Reset02_Channel.setForeground(new java.awt.Color(255, 255, 255));
        Reset02_Channel.setText("Reset");
        Reset02_Channel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset02_ChannelActionPerformed(evt);
            }
        });
        jPanel1456.add(Reset02_Channel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 810, 120, 40));

        Submit_Channel.setBackground(new java.awt.Color(255, 51, 51));
        Submit_Channel.setForeground(new java.awt.Color(255, 255, 255));
        Submit_Channel.setText("login");
        Submit_Channel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_ChannelActionPerformed(evt);
            }
        });
        jPanel1456.add(Submit_Channel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 810, 120, 40));

        JLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/20191010_stamp_03.jpg"))); // NOI18N
        JLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1456.add(JLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 730, 290));

        UserPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserPass.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1456.add(UserPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 720, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/982a.jpg"))); // NOI18N
        jPanel1456.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 230, 230));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Please Enter Your User Name & Password :");
        jPanel1456.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 520, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1456, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1456, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        MainMenu MM=new MainMenu();
        setVisible(false);
        MM.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void Reset02_ChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset02_ChannelActionPerformed
        // TODO add your handling code here:
     //   Cname_Channel.setText(null);
       // Nic_Channel.setText(null);
        //Cusphn_Channel.setText(null);
    }//GEN-LAST:event_Reset02_ChannelActionPerformed

    private void Submit_ChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_ChannelActionPerformed
        // TODO add your handling code here:
        
        try 
        {
            String UP=UserPass.getText();
             
            byte[] byte_pwd=UP.getBytes();
            MessageDigest md5;
            md5 = MessageDigest.getInstance("md5");
            md5.update(byte_pwd);
            byte[] BytePass=md5.digest();
            UserPassEncript=DatatypeConverter.printHexBinary(BytePass);
          
            try 
            {
                String UserCheck="select * from user where User_name='"+UserName.getText()+"'";
                ps = conn.prepareStatement(UserCheck);
                rs=ps.executeQuery();
                if(rs.next())
                {
                     //System.out.println(rs.getString("Password"));
                    
                    if(UserPassEncript.equals(rs.getString("Password")) && UserName.getText().equals(rs.getString("User_name")))
                    {
                        AdminSideFunctions ADF=new AdminSideFunctions();
                        setVisible(false);
                        ADF.setVisible(true);
                        
                    }
                    
                    
                    
                }
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(AdminSide.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } 
        catch (NoSuchAlgorithmException ex) 
        {
            Logger.getLogger(AdminSide.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        /*String channelling_SelectSpecialist = EC.Specia_Channel.getSelectedItem().toString();
        String channelling_SelectHospital = EC.Hospital_Channel.getSelectedItem().toString();
        Date channelling_AppointDate = EC.Date_Channel.getDate();*/

        // System.out.println(abc);
    /*    try
        {

            if(Doctor_name.equals("") && channelling_SelectSpecialist.equals("SELECT SPECIALISATION AREA") && channelling_SelectHospital.equals("SELECT YOUR HOSPITAL") && Cname_Channel.getText().equals("") &&  Cusphn_Channel.getText().equals("") && Nic_Channel.getText().equals("") )
            {
                //Validate_Bill.setText("Please Fill Every Fields");

            }
            else
            {
                //float B_Payment=Float.parseFloat(Bill_Payment.getText());
                int Nic_chann_cus=Integer.parseInt(Nic_Channel.getText());
                int Phn_no_cus=Integer.parseInt(Cusphn_Channel.getText());

                //String BT_SelectValue = BillType.getSelectedItem().toString();

                //Billtype_Check.setVisible(false);
                //Doctor_name`, `Specialization`, `Hospital`, `Appointment_date`, `Cus_name`, `Customer_NIC`, `Customer_Phone_No` FROM `e_channelling
                String DoctorChannellingData="insert into e_channelling(Doctor_name,Specialization,Hospital,Appointment_date,Cus_name,Customer_NIC,Customer_Phone_No) values('"+Doctor_name+"','"+channelling_SelectSpecialist+"','"+channelling_SelectHospital+"','"+channelling_AppointDate+"','"+Cname_Channel.getText()+"',"+Nic_Channel.getText()+","+Cusphn_Channel.getText()+")";
                System.out.println(DoctorChannellingData);
                PreparedStatement ps =conn.prepareStatement(DoctorChannellingData);
                ps.execute();

            }
        }
        catch (Exception e)
        {

            System.out.println(e);
        }
        /*  Bill_Payment.setText("");
        Bill_Phn.setText("");
        Bill_UserNme.setText("");
        Bill_Account1.setText("");*/
    }//GEN-LAST:event_Submit_ChannelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLabel1;
    private javax.swing.JButton Reset02_Channel;
    private javax.swing.JButton Submit_Channel;
    private javax.swing.JTextField UserName;
    private javax.swing.JPasswordField UserPass;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1456;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
