/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postOffice;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lakshan
 */
public class AdminSideSendDailyParcelPost extends javax.swing.JFrame {
Connection conn=DBconnection.connect();
ResultSet rs =null;
int numberRow;
    /**
     * Creates new form AdminSideSendDailyParcelPost
     */
    public AdminSideSendDailyParcelPost() {
        initComponents();
         try
        {
            String SelectASMoneyQuerery="select * from parcel_post";
            PreparedStatement ps =conn.prepareStatement(SelectASMoneyQuerery);
            //ps.execute();
            rs=ps.executeQuery();
            AdminSideParcelPost.setModel(DbUtils.resultSetToTableModel(rs));
           
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1456 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        Reset02_Channel = new javax.swing.JButton();
        PpleAiedSumbit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        PpleAiedCAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AdminSideParcelPost = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        ParcelPostCount = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ParcelPostCheck = new javax.swing.JButton();
        ParcelPostDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1456.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1456.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1456.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/DOP_header.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1456.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, -1));

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/back3.png"))); // NOI18N
        jButton8.setText("GO Back");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1456.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 45));

        Reset02_Channel.setBackground(new java.awt.Color(255, 51, 51));
        Reset02_Channel.setForeground(new java.awt.Color(255, 255, 255));
        Reset02_Channel.setText("Reset");
        Reset02_Channel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset02_ChannelActionPerformed(evt);
            }
        });
        jPanel1456.add(Reset02_Channel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 810, 120, 40));

        PpleAiedSumbit.setBackground(new java.awt.Color(255, 51, 51));
        PpleAiedSumbit.setForeground(new java.awt.Color(255, 255, 255));
        PpleAiedSumbit.setText("login");
        PpleAiedSumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PpleAiedSumbitActionPerformed(evt);
            }
        });
        jPanel1456.add(PpleAiedSumbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 810, 120, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Amount");
        jPanel1456.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, 150, 30));

        PpleAiedCAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PpleAiedCAmount.setToolTipText("");
        PpleAiedCAmount.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PpleAiedCAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PpleAiedCAmountActionPerformed(evt);
            }
        });
        jPanel1456.add(PpleAiedCAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 720, 250, 30));

        AdminSideParcelPost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        AdminSideParcelPost.setToolTipText("");
        jScrollPane1.setViewportView(AdminSideParcelPost);

        jPanel1456.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 690, 220));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-Channelling /");
        jPanel1456.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 210, -1));

        jLabel3.setFont(new java.awt.Font("4u-Malith", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("wka;¾cd,fhka pek,a lsÍu");
        jPanel1456.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 350, 30));

        panel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bill Payme t Count");
        jLabel1.setToolTipText("");

        ParcelPostCount.setFont(new java.awt.Font("Leelawadee UI", 0, 60)); // NOI18N
        ParcelPostCount.setForeground(new java.awt.Color(255, 255, 255));
        ParcelPostCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ParcelPostCount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ParcelPostCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParcelPostCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1456.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 150, 120));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ParcelPostCheck.setText("Select Date");
        ParcelPostCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcelPostCheckActionPerformed(evt);
            }
        });

        ParcelPostDateChooser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ParcelPostDateChooserAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ParcelPostDateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParcelPostDateChooserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ParcelPostDateChooserMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ParcelPostDateChooserMousePressed(evt);
            }
        });
        ParcelPostDateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ParcelPostDateChooserKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(ParcelPostCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParcelPostDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ParcelPostCheck)
                    .addComponent(ParcelPostDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jPanel1456.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 260, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1456, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1456, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        MainMenu MM=new MainMenu();
        setVisible(false);
        MM.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void Reset02_ChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset02_ChannelActionPerformed
        // TODO add your handling code here:
        //   Cname_Channel.setText(null);
        // Nic_Channel.setText(null);
        //Cusphn_Channel.setText(null);
    }//GEN-LAST:event_Reset02_ChannelActionPerformed

    private void PpleAiedSumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PpleAiedSumbitActionPerformed

    }//GEN-LAST:event_PpleAiedSumbitActionPerformed

    private void PpleAiedCAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PpleAiedCAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PpleAiedCAmountActionPerformed

    private void ParcelPostCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcelPostCheckActionPerformed
        // TODO add your handling code here:

        int a=ParcelPostDateChooser.getCalendar().get(Calendar.MONTH)+1;
        int b=ParcelPostDateChooser.getCalendar().get(Calendar.DATE);
        int c=ParcelPostDateChooser.getCalendar().get(Calendar.YEAR);
        String SelectedDate=c+"-"+"0"+a+"-"+b;
        //String SelectedDate=""+MoneyOrderlDateChooser.getDate();
        System.out.println(SelectedDate);
        //EchannelCount.setText(SelectedDate);
        try
        {
            String SelectASMoneyQuerery="select * from parcel_post WHERE Date LIKE '%"+SelectedDate+"%'";
            PreparedStatement ps =conn.prepareStatement(SelectASMoneyQuerery);
            //ps.execute();
            rs=ps.executeQuery();
            AdminSideParcelPost.setModel(DbUtils.resultSetToTableModel(rs));
           /* while(rs.next()){
                numberRow = rs.getInt("No");

            }
            if(numberRow<9)
            ParcelPostCount.setText("0"+numberRow);
            else
            ParcelPostCount.setText(""+numberRow);*/
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        // System.out.println("Current date : " + (now.get(Calendar.MONTH) + 1) + "-"+ now.get(Calendar.DATE) + "-" + now.get(Calendar.YEAR));
        //; //
    }//GEN-LAST:event_ParcelPostCheckActionPerformed

    private void ParcelPostDateChooserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ParcelPostDateChooserAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ParcelPostDateChooserAncestorAdded

    private void ParcelPostDateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParcelPostDateChooserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ParcelPostDateChooserMouseClicked

    private void ParcelPostDateChooserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParcelPostDateChooserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ParcelPostDateChooserMouseEntered

    private void ParcelPostDateChooserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParcelPostDateChooserMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ParcelPostDateChooserMousePressed

    private void ParcelPostDateChooserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ParcelPostDateChooserKeyPressed
        // TODO add your handling code here:.
    }//GEN-LAST:event_ParcelPostDateChooserKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSideSendDailyParcelPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSideSendDailyParcelPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSideSendDailyParcelPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSideSendDailyParcelPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSideSendDailyParcelPost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable AdminSideParcelPost;
    public javax.swing.JButton ParcelPostCheck;
    public javax.swing.JLabel ParcelPostCount;
    private com.toedter.calendar.JDateChooser ParcelPostDateChooser;
    private javax.swing.JTextField PpleAiedCAmount;
    private javax.swing.JButton PpleAiedSumbit;
    private javax.swing.JButton Reset02_Channel;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel1456;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
