/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postOffice;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Lakshan
 */
public class BillPayment extends javax.swing.JFrame {
 ResultSet rs =null;
    Connection conn=DBconnection.connect();
    
    /**
     * Creates new form BillPayment
     */
    public BillPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Bill_UserNme = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BillType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Bill_Phn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Bill_Payment = new javax.swing.JTextField();
        Bill_Submit = new javax.swing.JButton();
        Bill_Reset = new javax.swing.JButton();
        Bill_Account1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Billtype_Check = new javax.swing.JLabel();
        Validate_Bill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/DOP_header.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setText("Bill Payment /");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 180, 30));

        jLabel3.setFont(new java.awt.Font("4u-Malith", 0, 28)); // NOI18N
        jLabel3.setText("ì,am;a f.úu");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 180, 30));

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/back3.png"))); // NOI18N
        jButton8.setText("GO Back");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/WireIcon-300x110.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 300, 120));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Bill Type");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 110, 30));

        Bill_UserNme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bill_UserNme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_UserNmeActionPerformed(evt);
            }
        });
        jPanel1.add(Bill_UserNme, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 230, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Customer Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 130, 30));

        BillType.setBackground(new java.awt.Color(255, 51, 51));
        BillType.setEditable(true);
        BillType.setForeground(new java.awt.Color(255, 255, 255));
        BillType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bill Type", "Electricity Bill", "Water Bill", "Mobitel Bill", "SLT Bill", "Dialog Bill" }));
        jPanel1.add(BillType, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Phone No");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 110, 30));

        Bill_Phn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bill_Phn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_PhnActionPerformed(evt);
            }
        });
        jPanel1.add(Bill_Phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 230, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Payment");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 110, 30));

        Bill_Payment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bill_Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_PaymentActionPerformed(evt);
            }
        });
        jPanel1.add(Bill_Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, 230, 30));

        Bill_Submit.setBackground(new java.awt.Color(255, 51, 51));
        Bill_Submit.setForeground(new java.awt.Color(255, 255, 255));
        Bill_Submit.setText("Submit");
        Bill_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Bill_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 810, 120, 40));

        Bill_Reset.setBackground(new java.awt.Color(255, 51, 51));
        Bill_Reset.setForeground(new java.awt.Color(255, 255, 255));
        Bill_Reset.setText("Reset");
        Bill_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_ResetActionPerformed(evt);
            }
        });
        jPanel1.add(Bill_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 810, 120, 40));

        Bill_Account1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bill_Account1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_Account1ActionPerformed(evt);
            }
        });
        jPanel1.add(Bill_Account1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 230, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Account No");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 110, 30));

        Billtype_Check.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(Billtype_Check, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 406, 130, 30));
        jPanel1.add(Validate_Bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 726, 330, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        MainMenu MM=new MainMenu();
        setVisible(false);
        MM.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void Bill_UserNmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_UserNmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_UserNmeActionPerformed

    private void Bill_PhnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_PhnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_PhnActionPerformed

    private void Bill_PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_PaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_PaymentActionPerformed

    private void Bill_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_SubmitActionPerformed
        // TODO add your handling code here:
       
        try 
        {
             
        
            if(Bill_Payment.getText().equals("") && Bill_Phn.getText().equals("") && Bill_UserNme.getText().equals("") && Bill_Account1.getText().equals(""))
            {
                Validate_Bill.setText("Please Fill Every Fields");
                
            }    
            else
            {
              float B_Payment=Float.parseFloat(Bill_Payment.getText());
              int B_Phn=Integer.parseInt(Bill_Phn.getText());
              int B_Acc=Integer.parseInt(Bill_Account1.getText()); 
              String BT_SelectValue = BillType.getSelectedItem().toString();
                
                if("Select Bill Type".equals(BT_SelectValue))
                {
                    Billtype_Check.setText("Select Correct Bill Type");
                }
                else 
                {
                    Billtype_Check.setVisible(false);
                    String BillPayAdd="insert into bill_payments(User_Name,Account_No,Bill_Type,Phone_No,Amount) values('"+Bill_UserNme.getText()+"',"+B_Acc+",'"+BT_SelectValue+"',"+B_Phn+","+B_Payment+")";
                    PreparedStatement ps =conn.prepareStatement(BillPayAdd);
                    ps.execute();     
                }
               
            } 
        }
        catch (Exception e) 
        {
            
             System.out.println(e);
        }
        Bill_Payment.setText("");
        Bill_Phn.setText("");
        Bill_UserNme.setText("");
        Bill_Account1.setText("");
    }//GEN-LAST:event_Bill_SubmitActionPerformed

    private void Bill_Account1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_Account1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_Account1ActionPerformed

    private void Bill_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_ResetActionPerformed
        // TODO add your handling code here:
        Bill_UserNme.setText(null);
        Bill_Account1.setText(null);
        Bill_Phn.setText(null);
        Bill_Payment.setText(null);
    }//GEN-LAST:event_Bill_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BillType;
    private javax.swing.JTextField Bill_Account1;
    private javax.swing.JTextField Bill_Payment;
    private javax.swing.JTextField Bill_Phn;
    private javax.swing.JButton Bill_Reset;
    private javax.swing.JButton Bill_Submit;
    private javax.swing.JTextField Bill_UserNme;
    private javax.swing.JLabel Billtype_Check;
    private javax.swing.JLabel Validate_Bill;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
