/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postOffice;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author Lakshan
 */
public class ParcelService extends javax.swing.JFrame {
    ResultSet rs =null;
    Connection conn=DBconnection.connect();
     String PS_SelectValue;
     float width_par;
    /**
     * Creates new form ParcelService
     */
    public ParcelService() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Rphno_Par = new javax.swing.JTextField();
        Sname_Par = new javax.swing.JTextField();
        Sadd_Par = new javax.swing.JTextField();
        Sphno_Par = new javax.swing.JTextField();
        Weigth_kg = new javax.swing.JTextField();
        Rname_Par = new javax.swing.JTextField();
        Radd_Par = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Amount_Par = new javax.swing.JLabel();
        WeightScaleType = new javax.swing.JComboBox<>();
        Weigth_g = new javax.swing.JTextField();
        g = new javax.swing.JLabel();
        kg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/DOP_header.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setText("Parcel Service /");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 30));

        jLabel3.setFont(new java.awt.Font("4u-Malith", 0, 28)); // NOI18N
        jLabel3.setText("md¾i,a fiajdj");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 180, 30));

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/back3.png"))); // NOI18N
        jButton8.setText("GO Back");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 45));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Amount (Rs.)");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sender Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sender Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Sender Ph No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Weigth");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Reciver Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 130, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Reciver Address");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 130, 30));

        Rphno_Par.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rphno_Par.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rphno_ParMouseClicked(evt);
            }
        });
        jPanel1.add(Rphno_Par, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 230, 30));

        Sname_Par.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sname_Par.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sname_ParMouseClicked(evt);
            }
        });
        Sname_Par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sname_ParActionPerformed(evt);
            }
        });
        jPanel1.add(Sname_Par, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 230, 30));

        Sadd_Par.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sadd_Par.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sadd_ParMouseClicked(evt);
            }
        });
        jPanel1.add(Sadd_Par, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 230, 30));

        Sphno_Par.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sphno_Par.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sphno_ParMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Sphno_ParMouseEntered(evt);
            }
        });
        jPanel1.add(Sphno_Par, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 230, 30));

        Weigth_kg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Weigth_kg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Weigth_kgMouseClicked(evt);
            }
        });
        Weigth_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Weigth_kgActionPerformed(evt);
            }
        });
        Weigth_kg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Weigth_kgKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Weigth_kgKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Weigth_kgKeyTyped(evt);
            }
        });
        jPanel1.add(Weigth_kg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 230, 30));

        Rname_Par.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rname_Par.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rname_ParMouseClicked(evt);
            }
        });
        jPanel1.add(Rname_Par, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 230, 30));

        Radd_Par.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Radd_Par.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Radd_ParMouseClicked(evt);
            }
        });
        jPanel1.add(Radd_Par, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 230, 30));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check Parcel Post Rate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 820, 180, 40));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 820, 110, 40));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 820, 110, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postOffice/parcel_post.gif"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 370, 120));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Reciver Ph No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 130, 30));

        Amount_Par.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        Amount_Par.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Amount_Par.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(Amount_Par, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 630, 140, 110));

        WeightScaleType.setBackground(new java.awt.Color(255, 51, 51));
        WeightScaleType.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        WeightScaleType.setForeground(new java.awt.Color(255, 255, 255));
        WeightScaleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Scale", "gram", "kilogram" }));
        WeightScaleType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WeightScaleTypeMouseClicked(evt);
            }
        });
        WeightScaleType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightScaleTypeActionPerformed(evt);
            }
        });
        jPanel1.add(WeightScaleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 520, 110, 30));

        Weigth_g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Weigth_gMouseClicked(evt);
            }
        });
        Weigth_g.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Weigth_gKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Weigth_gKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Weigth_gKeyTyped(evt);
            }
        });
        jPanel1.add(Weigth_g, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 230, 30));

        g.setText("g");
        jPanel1.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        kg.setText("kg");
        jPanel1.add(kg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //System.out.println(PS_SelectValue);
        
        if(PS_SelectValue == "kilogram")
        {
                this.width_par=Float.parseFloat(Weigth_kg.getText());  
                System.out.println("value is "+width_par);
        }
        else if(PS_SelectValue=="gram")
        {
                 this.width_par=Float.parseFloat(Weigth_g.getText());
        }
        else 
        {
                System.out.println("NULL");
        }
          try 
          {
              System.out.println(width_par);
            int SPhn_no_par=Integer.parseInt(Sphno_Par.getText());
            int RPhn_no_par=Integer.parseInt(Rphno_Par.getText());
            float amount_par=Float.parseFloat(Amount_Par.getText());    
          String ParcelAdd="insert into parcel_post(Sender_Name,Sender_Address,Sender_Ph_No,Weigth,Reciver_Name,Reciver_Address,Reciver_Ph_No,Amount) values('"+Sname_Par.getText()+"','"+Sadd_Par.getText()+"',"+SPhn_no_par+","+width_par+",'"+Rname_Par.getText()+"','"+Radd_Par.getText()+"',"+RPhn_no_par+","+amount_par+")";
         
            //String Add="insert into parcel_post(Sender_Name)values('abc')";
            System.out.println(ParcelAdd);
            PreparedStatement ps =conn.prepareStatement(ParcelAdd);
            ps.execute();
            //Notice_table.setModel(DbUtils.resultSetToTableModel(rs));
            
        } 
          catch (NumberFormatException | SQLException e) 
        {
            
             System.out.println(e);
        }
        Sphno_Par.setText("");
        Weigth_kg.setText("");
        Rphno_Par.setText("");
        Amount_Par.setText("");
        Sname_Par.setText("");
        Sadd_Par.setText("");
        Rname_Par.setText("");
        Radd_Par.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Sname_ParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sname_ParActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sname_ParActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        MainMenu MM=new MainMenu();
        setVisible(false);
        MM.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void Weigth_kgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Weigth_kgKeyTyped
        // TODO add your handling code here:
             
            
       
        
    }//GEN-LAST:event_Weigth_kgKeyTyped

    private void Weigth_kgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Weigth_kgKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_Weigth_kgKeyPressed

    private void Weigth_kgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Weigth_kgKeyReleased
        // TODO add your handling code here:
        WeightScaleType.setVisible(true);
         try {
             
             if(Weigth_kg.getText().length() != 0){
                 double ParWeight=Double.parseDouble(Weigth_kg.getText());
                 ParWeight=ParWeight*1000;
                 if(0<ParWeight && ParWeight<250){
                    
                     Amount_Par.setText(String.valueOf(90.00));
                 }
                 else if(250<=ParWeight && ParWeight<500){
                    Amount_Par.setText(String.valueOf(110.00));
                 }
                 else if(500<=ParWeight && ParWeight<1000){
                   Amount_Par.setText(String.valueOf(130.00));
                 }
                 else if(1000<=ParWeight && ParWeight<1500){
                      Amount_Par.setText(String.valueOf(150.00));
                 }
                 else if(1500<=ParWeight && ParWeight<2000){
                      Amount_Par.setText(String.valueOf(200.00));
                 }
                 else if(2000<=ParWeight && ParWeight<2500){
                      Amount_Par.setText(String.valueOf(250.00));
                 }
                 else if(2500<=ParWeight && ParWeight<3000){
                      Amount_Par.setText(String.valueOf(300.00));
                 }
                 else if(3000<=ParWeight && ParWeight<4000){
                      Amount_Par.setText(String.valueOf(350.00));
                 }
                 else if(4000<=ParWeight && ParWeight<5000){
                      Amount_Par.setText(String.valueOf(400.00));
                 }
                 else if(5000<=ParWeight && ParWeight<6000){
                      Amount_Par.setText(String.valueOf(450.00));
                 }
                 else if(6000<=ParWeight && ParWeight<7000){
                     Amount_Par.setText(String.valueOf(500.00));
                 }
                 else if(7000<=ParWeight && ParWeight<8000){
                      Amount_Par.setText(String.valueOf(550.00));
                 }
                 else if(8000<=ParWeight && ParWeight<9000){
                      Amount_Par.setText(String.valueOf(600.00));
                 }
                 else if(9000<=ParWeight && ParWeight<10000){
                      Amount_Par.setText(String.valueOf(650.00));
                 }
                  else if(10000<=ParWeight && ParWeight<11000){
                      Amount_Par.setText(String.valueOf(700.00));
                 }
                  else if(11000<=ParWeight && ParWeight<12000){
                      Amount_Par.setText(String.valueOf(750.00));
                 }
                  else if(12000<=ParWeight && ParWeight<13000){
                      Amount_Par.setText(String.valueOf(800.00));
                 }
                  else if(13000<=ParWeight && ParWeight<14000){
                      Amount_Par.setText(String.valueOf(850.00));
                 }
                  else if(14000<=ParWeight && ParWeight<15000){
                      Amount_Par.setText(String.valueOf(900.00));
                 }
                  else if(15000<=ParWeight && ParWeight<16000){
                      Amount_Par.setText(String.valueOf(950.00));
                 }
                  else if(16000<=ParWeight && ParWeight<17000){
                      Amount_Par.setText(String.valueOf(1000.00));
                 }
                  else if(17000<=ParWeight && ParWeight<18000){
                      Amount_Par.setText(String.valueOf(1050.00));
                 }
                  else if(18000<=ParWeight && ParWeight<19000){
                      Amount_Par.setText(String.valueOf(1100.00));
                 }
                  else if(19000<=ParWeight && ParWeight<=20000){
                      Amount_Par.setText(String.valueOf(1150.00));
                 }

                 
             } else {
                 Amount_Par.setText(null);
             }
              } catch (Exception e) {
        }

        
    }//GEN-LAST:event_Weigth_kgKeyReleased

    private void Weigth_kgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Weigth_kgMouseClicked
        // TODO add your handling code here:
        WeightScaleType.setVisible(true);
    }//GEN-LAST:event_Weigth_kgMouseClicked

    private void Sname_ParMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sname_ParMouseClicked
        // TODO add your handling code here:
        WeightScaleType.setVisible(false);
    }//GEN-LAST:event_Sname_ParMouseClicked

    private void Sadd_ParMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sadd_ParMouseClicked
        // TODO add your handling code here:
        WeightScaleType.setVisible(false);
    }//GEN-LAST:event_Sadd_ParMouseClicked

    private void Sphno_ParMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sphno_ParMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Sphno_ParMouseEntered

    private void Sphno_ParMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sphno_ParMouseClicked
        // TODO add your handling code here:
        WeightScaleType.setVisible(false);
    }//GEN-LAST:event_Sphno_ParMouseClicked

    private void Rname_ParMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rname_ParMouseClicked
        // TODO add your handling code here:
        WeightScaleType.setVisible(false);
    }//GEN-LAST:event_Rname_ParMouseClicked

    private void Radd_ParMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Radd_ParMouseClicked
        // TODO add your handling code here:
        WeightScaleType.setVisible(false);
    }//GEN-LAST:event_Radd_ParMouseClicked

    private void Rphno_ParMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rphno_ParMouseClicked
        // TODO add your handling code here:
        WeightScaleType.setVisible(false);
    }//GEN-LAST:event_Rphno_ParMouseClicked

    private void WeightScaleTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightScaleTypeActionPerformed
        // TODO add your handling code here:
         this.PS_SelectValue = WeightScaleType.getSelectedItem().toString();
         System.out.println(PS_SelectValue);
        if(PS_SelectValue=="gram"){
            Weigth_g.setVisible(true);
            Weigth_kg.setVisible(false);
            g.setVisible(true);
            kg.setVisible(false);
        }else if(PS_SelectValue=="kilogram"){
            Weigth_g.setVisible(false);
            Weigth_kg.setVisible(true);
             kg.setVisible(true);
            g.setVisible(false);
        }
        else{}
    }//GEN-LAST:event_WeightScaleTypeActionPerformed

    private void WeightScaleTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WeightScaleTypeMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_WeightScaleTypeMouseClicked

    private void Weigth_gMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Weigth_gMouseClicked
        // TODO add your handling code here:
        WeightScaleType.setVisible(true);
    }//GEN-LAST:event_Weigth_gMouseClicked

    private void Weigth_gKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Weigth_gKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Weigth_gKeyPressed

    private void Weigth_gKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Weigth_gKeyReleased
        // TODO add your handling code here:
        WeightScaleType.setVisible(true);
         try 
         {
             
             if(Weigth_g.getText().length() != 0){
                 int ParWeight=Integer.parseInt(Weigth_g.getText());
                 System.out.println(ParWeight);
                 if(0<ParWeight && ParWeight<250){
                    
                     Amount_Par.setText(String.valueOf(90.00));
                 }
                 else if(250<=ParWeight && ParWeight<500){
                    Amount_Par.setText(String.valueOf(110.00));
                 }
                 else if(500<=ParWeight && ParWeight<1000){
                   Amount_Par.setText(String.valueOf(130.00));
                 }
                 else if(1000<=ParWeight && ParWeight<1500){
                      Amount_Par.setText(String.valueOf(150.00));
                 }
                 else if(1500<=ParWeight && ParWeight<2000){
                      Amount_Par.setText(String.valueOf(200.00));
                 }
                 else if(2000<=ParWeight && ParWeight<2500){
                      Amount_Par.setText(String.valueOf(250.00));
                 }
                 else if(2500<=ParWeight && ParWeight<3000){
                      Amount_Par.setText(String.valueOf(300.00));
                 }
                 else if(3000<=ParWeight && ParWeight<4000){
                      Amount_Par.setText(String.valueOf(350.00));
                 }
                 else if(4000<=ParWeight && ParWeight<5000){
                      Amount_Par.setText(String.valueOf(400.00));
                 }
                 else if(5000<=ParWeight && ParWeight<6000){
                      Amount_Par.setText(String.valueOf(450.00));
                 }
                 else if(6000<=ParWeight && ParWeight<7000){
                     Amount_Par.setText(String.valueOf(500.00));
                 }
                 else if(7000<=ParWeight && ParWeight<8000){
                      Amount_Par.setText(String.valueOf(550.00));
                 }
                 else if(8000<=ParWeight && ParWeight<9000){
                      Amount_Par.setText(String.valueOf(600.00));
                 }
                 else if(9000<=ParWeight && ParWeight<10000){
                      Amount_Par.setText(String.valueOf(650.00));
                 }
                  else if(10000<=ParWeight && ParWeight<11000){
                      Amount_Par.setText(String.valueOf(700.00));
                 }
                  else if(11000<=ParWeight && ParWeight<12000){
                      Amount_Par.setText(String.valueOf(750.00));
                 }
                  else if(12000<=ParWeight && ParWeight<13000){
                      Amount_Par.setText(String.valueOf(800.00));
                 }
                  else if(13000<=ParWeight && ParWeight<14000){
                      Amount_Par.setText(String.valueOf(850.00));
                 }
                  else if(14000<=ParWeight && ParWeight<15000){
                      Amount_Par.setText(String.valueOf(900.00));
                 }
                  else if(15000<=ParWeight && ParWeight<16000){
                      Amount_Par.setText(String.valueOf(950.00));
                 }
                  else if(16000<=ParWeight && ParWeight<17000){
                      Amount_Par.setText(String.valueOf(1000.00));
                 }
                  else if(17000<=ParWeight && ParWeight<18000){
                      Amount_Par.setText(String.valueOf(1050.00));
                 }
                  else if(18000<=ParWeight && ParWeight<19000){
                      Amount_Par.setText(String.valueOf(1100.00));
                 }
                  else if(19000<=ParWeight && ParWeight<=20000){
                      Amount_Par.setText(String.valueOf(1150.00));
                 }

                 
             } else {
                 Amount_Par.setText(null);
             }
             
            
        } 
         catch (Exception e) 
        {
        }
    }//GEN-LAST:event_Weigth_gKeyReleased

    private void Weigth_gKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Weigth_gKeyTyped
        // TODO add your handling code here:
          

    }//GEN-LAST:event_Weigth_gKeyTyped

    private void Weigth_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Weigth_kgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Weigth_kgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParcelService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParcelService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParcelService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParcelService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParcelService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount_Par;
    private javax.swing.JTextField Radd_Par;
    private javax.swing.JTextField Rname_Par;
    private javax.swing.JTextField Rphno_Par;
    private javax.swing.JTextField Sadd_Par;
    public static javax.swing.JTextField Sname_Par;
    private javax.swing.JTextField Sphno_Par;
    public javax.swing.JComboBox<String> WeightScaleType;
    public javax.swing.JTextField Weigth_g;
    public javax.swing.JTextField Weigth_kg;
    private javax.swing.JLabel g;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kg;
    // End of variables declaration//GEN-END:variables
}
